name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7", "9.2.5"]
        cabal: ["3.8.1.0"]
        os: [ubuntu-latest]

    steps:
    - name: Workaround runner image issue
      if: runner.os == 'Linux'
      # https://github.com/actions/runner-images/issues/7061
      run: sudo chown -R $USER /usr/local/.ghcup

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "LINUX: Install build environment (apt-get)"
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install liblmdb-dev
        sudo apt-get -y autoremove

    - name: Setup Haskell
      id: setup-haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        cabal-update: false

    - name: Cabal update
      run: cabal update

    - name: Record cabal dependencies
      id: record-deps
      run: |
        cabal build all --dry-run

    - name: Cache cabal store
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Install cabal dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks all

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
