name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.7", "9.2.5"]
        cabal: ["3.8.1.0"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: "Linux: Install system dependencies (apt-get)"
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install liblmdb-dev
        sudo apt-get -y autoremove

    - name: "MacOS: Install system dependencies (brew)"
      if: runner.os == 'macOS'
      run: |
        brew install lmdb

    - name: "Windows: Install system dependencies via pacman (msys2)"
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ghcup run -- pacman --noconfirm -S mingw-w64-x86_64-lmdb

    - name: "Windows: Update PATH"
      if: runner.os == 'Windows'
      run: |
        $env:PATH=("C:\msys64\mingw64\bin;{0}" -f $env:PATH)
        echo "PATH=$env:PATH" >> $env:GITHUB_ENV

    - name: Setup Haskell
      id: setup-haskell
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        cabal-update: false

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: "Linux/MacOS: Configure cabal.project.local"
      if: runner.os != 'Windows'
      run: |
        cp .github/workflows/cabal.project.local.Linux cabal.project.local

    - name: "Windows: configure cabal.project.local"
      if: runner.os == 'Windows'
      run: |
        cp .github/workflows/cabal.project.local.Windows cabal.project.local

    - name: Cabal update
      run: cabal update

    - name: Record cabal dependencies
      id: record-deps
      run: |
        cabal build all --dry-run

    - name: Cache cabal store
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-

    - name: Install cabal dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks all

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: cabal test all
